# 1) Attributes of the car colour, type, origin and the target variable stolen

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## Importing dataset

In [2]:
df = pd.read_csv('KNN1.csv')
dftest = pd.read_csv('KNN1_X_test.csv')
df.sample
df.head(10)

colour   type    origin stolen
0     Red  Sport  Domestic    Yes
1     Red  Sport  Domestic     No
2     Red  Sport  Domestic    Yes
3  Yellow  Sport  Domestic     No
4  Yellow  Sport  Imported    Yes
5  Yellow    SUV  Imported     No
6  Yellow    SUV  Imported    Yes
7  Yellow    SUV  Domestic     No
8     Red    SUV  Imported     No
9     Red  Sport  Imported    Yes

In [3]:
dftest.head()

colour type    origin
0    Red  SUV  Domestic

## Exploring dataset

In [4]:
df.dtypes

colour    object
type      object
origin    object
stolen    object
dtype: object

In [5]:
dftest.dtypes

colour    object
type      object
origin    object
dtype: object

## Data Pre-Processing

เราจะต้องทำการแปลง categorical column เป็น numerical column ด้วย onehot encoding และแปลง stolen จาก yes,no เป็น 0,1

In [6]:
# from sklearn.preprocessing import LabelEncoder

# # Example DataFrame
# data = {'colour': ['Red', 'Yellow', 'Blue']}
# df = pd.DataFrame(data)

# # Initialize LabelEncoder
# label_encoder = LabelEncoder()

# # Apply LabelEncoder on the 'colour' column
# df['colour_encoded'] = label_encoder.fit_transform(df['colour'])

# print(df)

In [7]:
df['stolen'] = df['stolen'].map({'Yes': 1, 'No': 0})
y_df = df[['stolen']]
df.drop(['stolen'],axis=1,inplace=True)
print(y_df)

   stolen
0       1
1       0
2       1
3       0
4       1
5       0
6       1
7       0
8       0
9       1


In [8]:
df['colour'] = df['colour'].map({'Red': 1, 'Yellow': 0})
df['type'] = df['type'].map({'Sport': 1, 'SUV': 0})
df['origin'] = df['origin'].map({'Imported': 1, 'Domestic': 0})
X_df = df
X = X_df.values

In [9]:
y = y_df.values
print(y)

[[1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]]


ทำการแปลงแบบเดียวกันกับ dftest

In [10]:
dftest['colour'] = dftest['colour'].map({'Red': 1, 'Yellow': 0})
dftest['type'] = dftest['type'].map({'Sport': 1, 'SUV': 0})
dftest['origin'] = dftest['origin'].map({'Imported': 1, 'Domestic': 0})

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_norm = scaler.fit_transform(X)
new = dftest.values
new = scaler.transform(new)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
neigh.fit(X_norm, y)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(metric='euclidean')

In [13]:
y_pred = neigh.predict(new)
print(y_pred)

[0]


จากการคาดการณ์ KNN สรุปได้ว่ารถจะไม่ถูกขโมย

## Finding best k for K-NN

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.6, random_state = 2)

In [15]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
X_test

array([[-1.        ,  1.        ,  0.57735027],
       [ 1.        ,  1.        , -1.73205081],
       [-1.        , -1.        ,  0.57735027],
       [ 1.        ,  1.        , -1.73205081],
       [-1.        , -1.        , -1.73205081],
       [ 1.        ,  1.        , -1.73205081]])

In [17]:
y_test

array([[1],
       [0],
       [0],
       [1],
       [0],
       [1]])

In [18]:
scores = []
for k in range(1,5):
  neigh = KNeighborsClassifier(n_neighbors=k,metric='euclidean')
  neigh.fit(X_train, y_train.ravel())
  scores.append([k,neigh.score(X_test,y_test)])

In [19]:
scores

[[1, 0.5], [2, 0.6666666666666666], [3, 0.5], [4, 0.5]]

In [20]:
scores.sort(key=lambda x: x[1], reverse=True)
print(f"Best k={scores[0][0]} with accuracy score:{scores[0][1]}")

Best k=2 with accuracy score:0.6666666666666666
